services:
  postgres:
    container_name: airLine-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airline
    ports:
        - "5441:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: airLine-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5051:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
