DELETE FROM ticket;
DELETE FROM person;
DELETE FROM flight;

ALTER TABLE ticket
    ALTER COLUMN id RESTART;
ALTER TABLE person
    ALTER COLUMN id RESTART;
ALTER TABLE flight
    ALTER COLUMN id RESTART;